FROM ubuntu:14.04

RUN apt-get dist-upgrade
RUN apt-get update
RUN apt-get -y install software-properties-common
RUN add-apt-repository ppa:mc3man/trusty-media
RUN apt-get update
RUN apt-get -y install ffmpeg

