deploy:
	cd draw; fn deploy --local myapp
	cd publish; fn deploy --local myapp
	cd detect-plates; fn deploy --local myapp
	cd detect-faces; fn deploy --local myapp
	cd alert; fn deploy --local myapp
	cd scraper; fn deploy --local myapp
	cd split-video; fn deploy --local myapp
